# Steps
# Install Sarracenia (sr) v3 from apt
# Install blobfuse2
#
# Intended usage : mount TARGET_DIR to an existing directory on host which itself is FUSE mounted to cloud storage
# e.g. via `s3fs` fow S3 buckets or `blobfuse2` for Azure blob storage containers
# 
# As a result, files written in TARGET_DIR get written to the cloud by virtue of TARGET_DIR being mapped to cloud.
# FUSE mounting directories on the host mean no credentials are included in -- or need to be passed to -- the image
FROM ubuntu:22.04 as base
# FROM python:3.10-slim-bullseye as base
LABEL org.opencontainers.image.authors="yves.moisan@ec.gc.ca"

# Duration (s) that sr3 will be running for; defaults to 60
ENV duration 60
# sr3 configuration file
ENV sr3_conf swob
# name of blobfuse2 configuration file to be supplied at run time
ENV blobfuse2_conf blobfuse2_config.yaml

#RUN apt update && apt-get -y install  \
#    && adduser --disabled-password --gecos '' g2c
RUN apt-get update &&  apt-get install -y curl gnupg software-properties-common sudo

RUN adduser --disabled-password --gecos '' g2c && adduser g2c sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers 
## \   && sudo echo 'user_allow_other' >> /etc/fuse.conf

USER g2c
WORKDIR /home/g2c

RUN sudo curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add - \
    && sudo apt-add-repository https://packages.microsoft.com/ubuntu/22.04/prod && sudo apt-get update \
    && sudo apt-get -y install blobfuse2 \
    && sudo chmod 777 /etc/fuse.conf \
    && sudo add-apt-repository ppa:ssc-hpc-chp-spc/metpx && sudo apt update \
    && sudo apt-get -y install metpx-sr3 python3-amqp

# The following cannot be done in the previous `RUN` e.g. after `chmod`; raises permission issues
RUN sudo echo 'user_allow_other' >> /etc/fuse.conf
# We have to create directories in /home/g2c for sr3 to work
# IMPORTANT : Running this image needs one docker mount to
# e.g.
# docker run -d \
# -e sr3_conf=swob -e duration=1000 -e blobfuse2_conf=blobfuse2_conf_yaml \
# --cap-add=SYS_ADMIN --device=/dev/fuse --security-opt apparmor:unconfined \ 
# -v /home/yves/.config/sr3/:/home/g2c/.config/sr3/ ymoisan/sr3-fuse  \
# image
RUN mkdir -p /home/g2c/.config/sr3/ && \
mkdir -p /home/g2c/.blobfuse2

CMD mkdir -p /home/g2c/output \
 && blobfuse2 mount /home/g2c/output --config-file=/home/g2c/.config/sr3/blobfuse2/$blobfuse2_conf \ 
    && sr3 start subscribe/$sr3_conf && sleep $duration && sr3 stop subscribe/$sr3_conf && sleep 20

